### ISSUE TITLE
rs485_connect hinst->serial->user_data = hinst 错误

### ISSUE THREAD

**Issue by wanghui0574xs** [qiyongzhong0/rt-thread-rs485#2]
函数 int rs485_connect(rs485_inst_t * hinst)

      hinst->serial->user_data = hinst;
      hinst->serial->rx_indicate = rs485_recv_ind_hook;
      hinst->status = 1;

      LOG_D("rs485 connect success.");

hinst->serial->user_data 本指向uart寄存器, 被误指向hist 对象了.

**Comment by wanghui0574xs** [comment]
rt_hw_serial_register函数 device->user_data   = data;
rt_hw_serial_register(&serial1, "uart1",
                          RT_DEVICE_FLAG_RDWR | RT_DEVICE_FLAG_INT_RX |
                          RT_DEVICE_FLAG_INT_TX |   RT_DEVICE_FLAG_DMA_RX,
                          uart);
serial1.userdata 指向了uart.

rs485_connect 函数 
hinst->serial->user_data = hinst; // 把serial的user_data执行hinst, 覆盖了uart

rs485_recv_ind_hook 函数
rs485_inst_t *hinst = (rs485_inst_t *)(dev->user_data); // 需要user_data是 hinst
这里矛盾了

**Comment by qiyongzhong0** [comment]
user_data是给驱动上层应用预留的，驱动占用是不合理的，最好改驱动！



齐永忠
电话：15810366850
北京国电通网络技术有限公司
北京市北京市昌平区陈家营西路4号院1号楼 嘉铭奥森产业园西塔6层 
邮政编码：100000
 
发件人： wanghui0574xs
发送时间： 2022-01-21 09:56
收件人： qiyongzhong0/rt-thread-rs485
抄送： Subscribed
主题： Re: [qiyongzhong0/rt-thread-rs485] rs485_connect hinst->serial->user_data = hinst 错误 (Issue #2)
rt_hw_serial_register函数 device->user_data = data;
rt_hw_serial_register(&serial1, "uart1",
RT_DEVICE_FLAG_RDWR | RT_DEVICE_FLAG_INT_RX |
RT_DEVICE_FLAG_INT_TX | RT_DEVICE_FLAG_DMA_RX,
uart);
serial1.userdata 指向了uart.
rs485_connect 函数
hinst->serial->user_data = hinst; // 把serial的user_data执行hinst, 覆盖了uart
rs485_recv_ind_hook 函数
rs485_inst_t *hinst = (rs485_inst_t *)(dev->user_data); // 需要user_data是 hinst
这里矛盾了
―
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanghui0574xs** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    看了rt-thread/bsp目录下的 at32, amp32, bm3803, rasberry pi等, 看到的usart.c 里的驱动 都是rt_hw_serial_register(&serial1, "uart1",                          RT_DEVICE_FLAG_RDWR | RT_DEVICE_FLAG_INT_RX,                          &uart1);
    
        
            
        
    serial.user_data 都是指向uart去的. 
    
          
        
            
    
        font{
            line-height: 1.5;
        }
    
***@***.***

        
    
     
    

    在2022年01月21日 ***@***.***> 写道： 




user_data是给驱动上层应用预留的，驱动占用是不合理的，最好改驱动！















齐永忠



电话：15810366850



北京国电通网络技术有限公司



北京市北京市昌平区陈家营西路4号院1号楼 嘉铭奥森产业园西塔6层 



邮政编码：100000



 



发件人： wanghui0574xs



发送时间： 2022-01-21 09:56



收件人： qiyongzhong0/rt-thread-rs485



抄送： Subscribed



主题： Re: [qiyongzhong0/rt-thread-rs485] rs485_connect hinst->serial->user_data = hinst 错误 (Issue #2)



rt_hw_serial_register函数 device->user_data = data;



rt_hw_serial_register(&serial1, "uart1",



RT_DEVICE_FLAG_RDWR | RT_DEVICE_FLAG_INT_RX |



RT_DEVICE_FLAG_INT_TX | RT_DEVICE_FLAG_DMA_RX,



uart);



serial1.userdata 指向了uart.



rs485_connect 函数



hinst->serial->user_data = hinst; // 把serial的user_data执行hinst, 覆盖了uart



rs485_recv_ind_hook 函数



rs485_inst_t *hinst = (rs485_inst_t *)(dev->user_data); // 需要user_data是 hinst



这里矛盾了



―



Reply to this email directly, view it on GitHub, or unsubscribe.



Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qiyongzhong0** [comment]
参考STM32的串口驱动改吧！



齐永忠
电话：15810366850
北京国电通网络技术有限公司
北京市北京市昌平区陈家营西路4号院1号楼 嘉铭奥森产业园西塔6层 
邮政编码：100000
 
发件人： wanghui0574xs
发送时间： 2022-01-21 10:56
收件人： qiyongzhong0/rt-thread-rs485
抄送： 齐永忠; Comment
主题： Re: [qiyongzhong0/rt-thread-rs485] rs485_connect hinst->serial->user_data = hinst 错误 (Issue #2)






font{ 
line-height: 1.6; 
} 
ul,ol{ 
padding-left: 20px; 
list-style-position: inside; 
} 







看了rt-thread/bsp目录下的 at32, amp32, bm3803, rasberry pi等, 看到的usart.c 里的驱动 都是rt_hw_serial_register(&serial1, "uart1", RT_DEVICE_FLAG_RDWR | RT_DEVICE_FLAG_INT_RX, &uart1);




serial.user_data 都是指向uart去的. 





font{
line-height: 1.5;
}

***@***.***






在2022年01月21日 ***@***.***> 写道： 




user_data是给驱动上层应用预留的，驱动占用是不合理的，最好改驱动！















齐永忠



电话：15810366850



北京国电通网络技术有限公司



北京市北京市昌平区陈家营西路4号院1号楼 嘉铭奥森产业园西塔6层 



邮政编码：100000







发件人： wanghui0574xs



发送时间： 2022-01-21 09:56



收件人： qiyongzhong0/rt-thread-rs485



抄送： Subscribed



主题： Re: [qiyongzhong0/rt-thread-rs485] rs485_connect hinst->serial->user_data = hinst 错误 (Issue #2)



rt_hw_serial_register函数 device->user_data = data;



rt_hw_serial_register(&serial1, "uart1",



RT_DEVICE_FLAG_RDWR | RT_DEVICE_FLAG_INT_RX |



RT_DEVICE_FLAG_INT_TX | RT_DEVICE_FLAG_DMA_RX,



uart);



serial1.userdata 指向了uart.



rs485_connect 函数



hinst->serial->user_data = hinst; // 把serial的user_data执行hinst, 覆盖了uart



rs485_recv_ind_hook 函数



rs485_inst_t *hinst = (rs485_inst_t *)(dev->user_data); // 需要user_data是 hinst



这里矛盾了



―



Reply to this email directly, view it on GitHub, or unsubscribe.



Triage notifications on the go with GitHub Mobile for iOS or Android. 



You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>







—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***> 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qiyongzhong0** [comment]
可以照此改动：




齐永忠
电话：15810366850
北京国电通网络技术有限公司
北京市北京市昌平区陈家营西路4号院1号楼 嘉铭奥森产业园西塔6层 
邮政编码：100000
 
发件人： wanghui0574xs
发送时间： 2022-01-21 10:56
收件人： qiyongzhong0/rt-thread-rs485
抄送： 齐永忠; Comment
主题： Re: [qiyongzhong0/rt-thread-rs485] rs485_connect hinst->serial->user_data = hinst 错误 (Issue #2)






font{ 
line-height: 1.6; 
} 
ul,ol{ 
padding-left: 20px; 
list-style-position: inside; 
} 







看了rt-thread/bsp目录下的 at32, amp32, bm3803, rasberry pi等, 看到的usart.c 里的驱动 都是rt_hw_serial_register(&serial1, "uart1", RT_DEVICE_FLAG_RDWR | RT_DEVICE_FLAG_INT_RX, &uart1);




serial.user_data 都是指向uart去的. 





font{
line-height: 1.5;
}

***@***.***






在2022年01月21日 ***@***.***> 写道： 




user_data是给驱动上层应用预留的，驱动占用是不合理的，最好改驱动！















齐永忠



电话：15810366850



北京国电通网络技术有限公司



北京市北京市昌平区陈家营西路4号院1号楼 嘉铭奥森产业园西塔6层 



邮政编码：100000







发件人： wanghui0574xs



发送时间： 2022-01-21 09:56



收件人： qiyongzhong0/rt-thread-rs485



抄送： Subscribed



主题： Re: [qiyongzhong0/rt-thread-rs485] rs485_connect hinst->serial->user_data = hinst 错误 (Issue #2)



rt_hw_serial_register函数 device->user_data = data;



rt_hw_serial_register(&serial1, "uart1",



RT_DEVICE_FLAG_RDWR | RT_DEVICE_FLAG_INT_RX |



RT_DEVICE_FLAG_INT_TX | RT_DEVICE_FLAG_DMA_RX,



uart);



serial1.userdata 指向了uart.



rs485_connect 函数



hinst->serial->user_data = hinst; // 把serial的user_data执行hinst, 覆盖了uart



rs485_recv_ind_hook 函数



rs485_inst_t *hinst = (rs485_inst_t *)(dev->user_data); // 需要user_data是 hinst



这里矛盾了



D



Reply to this email directly, view it on GitHub, or unsubscribe.



Triage notifications on the go with GitHub Mobile for iOS or Android. 



You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>







―Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***> 
―
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
